name: koom
description: "A puzzle alarm clock to help you wake up wisely."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'



dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^19.3.0
  audioplayers: ^6.0.0
  uuid: ^4.4.0
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  flutter_background_service: ^5.0.5
  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0



flutter:


  uses-material-design: true


  assets:
    - assets/audio/
